CREATE TABLE SAMPLE
(
sno integer NOT NULL,
sid integer NOT NULL,
sname varchar(20),
sd date,
CONSTRAINT pk_sid PRIMARY KEY(sid)
);



CREATE PROCEDURE sample_insert(_sno integer, _sid integer, _sname varchar, _sd date)
LANGUAGE SQL
AS $BODY$
INSERT INTO SAMPLE(sno, sid, sname, sd)
VALUES(_sno, _sid, _sname, _sd);
$BODY$;


CALL sample_insert(1, 101, 'aaa', '2020-08-22');


CALL sample_insert(2, 102, 'bbb', '2020-08-22');




CREATE TABLE accounts
(
accid int generated by default as identity,
accname varchar(20) not null,
balance dec(15,2) not null,
primary key(acc id)
);


insert into accounts (accname, balance)
values('mani', 10000);

insert into accounts (accname, balance)
values('velu', 20000);


create or replace procedure transfer(
sender int,
receiver int,
amount dec
)
language plpgsql
as $$
begin
update accounts
set balance = balance + amount
where id = receiver;
update accounts
set balance = balance - amount
where id = sender;
commit;
end;$$
;


call transfer(1,2,100);




create procedure wow()
language plpgsql
as $$
begin
create table table_check(i int);
commit;
insert into table_check values(9);
commit;
delete from table_check;
rollback;
end $$
;


call wow();


select * from table_check;
 


drop table table_check;

call wow();
select * from table_check;
 
